In [32]:
import tkinter as tk
from tkinter import filedialog, messagebox
import camelot
import pandas as pd
import os
import openpyxl

import re

def on_submit():
    pdf_file = entry_pdf.get()
    page_specification = entry_page.get()
    csv_file = entry_csv.get()

    try:
        # Split the page specification if it contains a dash
        if '-' in page_specification:
            start_page, end_page = map(int, page_specification.split('-'))
            pages = ','.join(map(str, range(start_page, end_page + 1)))
        
        #if none is specified the default pages are all pages between 3 & 20
        elif page_specification == "":
            pages = ','.join(map(str, range(3, 20 + 1)))
                                
        else:
            pages = page_specification

        wb = openpyxl.Workbook()
    
        for page_number in pages.split(','):
            
            #Specify table areas for pages where header is not detected since it's too far from table content
            #if page_number in ['5','6','9','10','11']:
                #table_areas = ['50,550,700,40']
            #else:
                #table_areas = None
            
            #define table areas so table + header are included in xlsx
            table_areas = ['50,550,740,40']
            
            #define row tolerance to ensure double row headers aren't separated for page 8&9
            if page_number in ['8','9']:
                row_tol = 9
            else:
                row_tol = 2
            
            tables = camelot.read_pdf(pdf_file, flavor='stream', pages=page_number, table_areas = table_areas, row_tol = row_tol)
            for i, table in enumerate(tables, start=1):
                df = table.df

                # Delete all'.'
                df = df.applymap(lambda x: x.replace('.', '') if isinstance(x, str) else x)
                
                # Replace all ',' with '.'
                df = df.applymap(lambda x: x.replace(',', '.') if isinstance(x, str) else x)
                
                # Apply transformations to each cell in the DataFrame
                df = df.applymap(lambda x: adjust_negative_number(x))
                # Create a new worksheet for each table
                ws = wb.create_sheet(title=f"Page_{page_number}_Table_{i}")
                for row_data in df.values.tolist():
                    formatted_row_data = []
                    for cell in row_data:
                        try:
                            cell = float(cell)
                            formatted_row_data.append(cell)
                        except ValueError:
                            formatted_row_data.append(cell)
                    ws.append(formatted_row_data)
                # Add empty rows after each table
                for _ in range(5):
                    ws.append([''] * len(df.columns))

        # Remove the default sheet created by openpyxl
        wb.remove(wb["Sheet"])

        # Determine output filename
        if not csv_file.strip():
            base_name = os.path.splitext(os.path.basename(pdf_file))[0]  # Use input PDF filename without extension
            directory = os.path.dirname(pdf_file)
            csv_file = os.path.join(directory, base_name)

        # Check if the file already exists
        if os.path.exists(csv_file + '.xlsx'):
            # File exists, ask for confirmation before overwriting
            confirm = messagebox.askyesno("File Exists", "The output file already exists. Do you want to overwrite it?")
            if not confirm:
                result_label.config(text="Submission canceled.")
                return

        # Save the workbook
        wb.save(csv_file + '.xlsx')
        result_label.config(text=f"All tables extracted and saved to {csv_file}.xlsx")
    except Exception as e:
        result_label.config(text=f"Error: {e}")


def adjust_negative_number(cell_value):
    if isinstance(cell_value, str) and re.match(r'\s*-.*', cell_value.strip()):
        return '-' + re.sub(r'\s+', '', cell_value.strip().lstrip('-'))
    return cell_value



def browse_pdf():
    file_path = filedialog.askopenfilename(filetypes=[("PDF Files", "*.pdf")])
    entry_pdf.delete(0, tk.END)
    entry_pdf.insert(0, file_path)

# Create the main window
root = tk.Tk()
root.title("PDF Table Extractor")

# Create and pack widgets
label_pdf = tk.Label(root, text="PDF File:")
label_pdf.grid(row=0, column=0, padx=10, pady=5, sticky="E")

entry_pdf = tk.Entry(root, width=30)
entry_pdf.grid(row=0, column=1, padx=10, pady=5)

button_browse_pdf = tk.Button(root, text="Browse", command=browse_pdf)
button_browse_pdf.grid(row=0, column=2, pady=5)

label_page = tk.Label(root, text="Page Range: \n (default is pages 3-20)")
label_page.grid(row=1, column=0, padx=10, pady=5, sticky="E")

entry_page = tk.Entry(root, width=30)  # Allow input of page range in the format 'start_page-end_page'
entry_page.grid(row=1, column=1, padx=10, pady=5)

label_csv = tk.Label(root, text="Excel File: \n (default is pdf name with .xlsx extension)")
label_csv.grid(row=2, column=0, padx=10, pady=5, sticky="E")

entry_csv = tk.Entry(root, width=30)
entry_csv.grid(row=2, column=1, padx=10, pady=5)

button_submit = tk.Button(root, text="Submit", command=on_submit)
button_submit.grid(row=3, column=1, pady=10)

result_label = tk.Label(root, text="")
result_label.grid(row=4, column=0, columnspan=3, pady=10)

# Start the main loop
root.mainloop()

In [3]:
import tkinter as tk
from tkinter import filedialog, messagebox
import camelot
import pandas as pd
import os
import openpyxl

import re

In [27]:
pdf_file = r"C:\Users\fabic\Documents\Hannah\202311_Owner_Reporting_Hilton_Vienna_Park.pdf"
table_areas = ['50,550,740,40']
page_number = '7'
#define row tolerance to ensure double row headers aren't separated for page 8&9
#if page_number in ['8','9']:
#    row_tol = 9
#else:
#    row_tol = 2

def adjust_negative_number(cell_value):
    if isinstance(cell_value, str) and re.match(r'\s*-.*', cell_value.strip()):
        return '-' + re.sub(r'\s+', '', cell_value.strip().lstrip('-'))
    return cell_value

In [28]:
tables = camelot.read_pdf(pdf_file, flavor='stream', pages=page_number, table_areas = table_areas, row_tol = row_tol)

df = tables[0].df

# Delete all'.'
df = df.applymap(lambda x: x.replace('.', '') if isinstance(x, str) else x)

# Apply transformations to each cell in the DataFrame
df = df.applymap(lambda x: adjust_negative_number(x))

In [30]:
display(df)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,P&L YTD,,,,,,,,,,,,,,
1,,,,Month - November,,,,in ´000,,,,YTD - November,,,
2,Actual TY,Budget,€ B/(W),% B/(W),Actual LY,% B/(W),Actual LY,Hilton Vienna Park,Actual TY,Budget,€ B/(W),% B/(W),Actual LY,% B/(W),Actual LY
3,19890,19890,-,-,19890,-,-,Available Rooms,221442,221442,-,-,221442,-,-
4,14490,14175,315,"2,2%",14292,198,"1,4%",Total Occupied Rooms (revenue rooms),167342,150135,17207,"11,5%",134208,33134,"24,7%"
5,21974,18566,3408,"18,4%",17610,4364,"24,8%",F&B Customers,226553,196234,30319,"15,5%",170418,56135,"32,9%"
6,16329,18566,(2237),"(12,1%)",17593,(1264),"(7,2%)",Outlet Customers,196021,196045,(24),"(0,0%)",153163,42858,"28,0%"
7,5645,-,5645,-,17,5628,"33105,9%",C&E Customers,30532,189,30343,"16054,5%",17255,13277,"76,9%"
8,"793,3","673,2","120,0","17,8%","704,4","88,9","12,6%",Food revenue,"6931,4","6609,1","322,3","4,9%","4875,8","2055,7","42,2%"
9,"236,7","178,3","(58,4)","(32,8%)","193,9","42,8","22,1%",Beverage Revenue,"1983,9","1883,3","(100,6)","(5,3%)","1620,0","363,9","22,5%"
10,"197,0","216,8","19,8","9,1%","179,9","(17,1)","(9,5%)",Food COS,"1899,1","2131,8","232,6","10,9%","1443,9","(455,2)","(31,5%)"
11,"34,4","26,0","(8,4)","(32,1%)","39,4","5,0","12,7%",Beverage COS,"299,7","281,3","(18,4)","(6,6%)","270,9","(28,8)","(10,6%)"
12,"1146,9","987,1","(159,8)","(16,2%)","984,0","(162,9)","(16,6%)",Total Payroll,"10611,5","10318,3","(293,3)","(2,8%)","8060,4","(2551,2)","(31,7%)"
13,"72,9%","71,3%","1,6 pts","2,2%","71,9%","1,0 pts","1,4%",Occupancy %,"75,6%","67,8%","7,8 pts","11,5%","60,6%","15,0 pts","24,7%"
14,"181,1","147,9","33,2","22,5%","170,3","10,8","6,4%",Average Rate,"187,8","167,5","20,3","12,1%","165,5","22,3","13,5%"
15,"132,0","105,4","26,5","25,2%","122,4","9,6","7,8%",REVPAR,"141,9","113,5","28,3","25,0%","100,3","41,6","41,5%"
16,"1776,5","1330,9","445,55","0,33","1449,78","326,7","22,5%",Transient Revenue,"19115,43","14102,9","5012,5","35,5%","13456,6","5658,9","42,1%"
17,"742,8","717,7","25,09","0,03","853,23","(110,4)","(12,9%)",Group Revenue,"11119,13","10088,8","1030,4","10,2%","7405,7","3713,4","50,1%"
18,"40,9","33,2","7,7","23,1%","29,5","11,4","38,6%",Permanent,"579,1","692,9","(113,7)","(16,4%)","694,0","(114,8)","(16,5%)"
19,"64,7","15,0","49,7","331,1%","101,6","(36,9)","(36,4%)",All Other Rm Revenue,"608,3","260,0","348,3","133,9%","650,5","(42,2)","(6,5%)"
20,"2624,8","2096,8","528,0","25,2%","2434,2","190,7","7,8%",Rooms Revenue,"31422,0","25144,6","6277,4","25,0%","22206,7","9215,3","41,5%"
21,"543,2","568,6","(25,3)","(4,5%)","497,8","45,4","9,1%",F&B - Outlets,"5778,8","5809,3","(30,5)","(0,5%)","4328,1","1450,7","33,5%"
22,"790,0","520,0","270,0","51,9%","807,4","(17,5)","(2,2%)",F&B - C&E,"5842,9","4965,0","877,9","17,7%","4184,5","1658,5","39,6%"
23,"1333,2","1088,6","244,6","22,5%","1305,3","27,9","2,1%",Total Food and Beverage Revenue,"11621,7","10774,3","847,4","7,9%","8512,6","3109,2","36,5%"
24,"33,1","28,1","5,0","17,8%","32,6","0,5","1,6%",Total Operating Dept Revenue,"382,2","273,4","108,7","39,8%","295,1","87,1","29,5%"
25,"56,1","43,7","12,3","28,2%","55,3","0,8","1,4%",Other Income,"1204,1","476,0","728,0","152,9%","1210,6","(6,5)","(0,5%)"
26,"89,2","71,8","17,3","24,1%","87,9","1,3","1,5%",Other Revenue,"1586,2","749,4","836,8","111,7%","1505,6","80,6","5,4%"
27,"4047,2","3257,3","789,9","24,3%","3827,3","219,9","5,7%",Total Revenue,"44629,9","36668,4","7961,5","21,7%","32224,9","12405,0","38,5%"
28,"235,2","248,6","13,4","5,4%","225,4","(9,9)","(4,4%)",Total Cost of Sales,"2256,9","2478,6","221,8","8,9%","1787,8","(469,1)","(26,2%)"
29,"24,8%","32,2%",,"7,4 pts","25,5%",,"0,7 pts",Food Cost %,"27,4%","32,3%",,"4,9 pts","29,6%",,"2,2 pts"
30,"14,5%","14,6%",,"0,1 pts","20,3%",,"5,8 pts",Beverage Cost %,"15,1%","14,9%",,"(0,2 pts)","16,7%",,"1,6 pts"
31,"865,0","752,6","(112,4)","(14,9%)","766,9","(98,1)","(12,8%)",Operating Payroll,"8042,8","7817,9","(225,0)","(2,9%)","6224,4","(1818,4)","(29,2%)"
32,"281,2","234,5","(46,6)","(19,9%)","217,1","(64,0)","(29,5%)",Overhead Payroll,"2561,5","2500,4","(61,1)","(2,4%)","1835,9","(725,5)","(39,5%)"
33,"28,3%","30,3%",,"2,0 pts","25,7%",,"(2,6 pts)",Payroll %,"23,8%","28,1%",,"4,4 pts","25,0%",,"1,2 pts"
34,"596,1","427,8","(168,3)","(39,3%)","686,5","90,4","13,2%",Operating Expense,"6054,1","4493,8","(1560,3)","(34,7%)","4563,5","(1490,6)","(32,7%)"
35,"248,3","514,2","265,8","51,7%","479,9","231,5","48,2%",Overhead Expense,"5744,4","5320,4","(424,1)","(8,0%)","4471,3","(1273,1)","(28,5%)"
36,"1821,4","1079,5","741,9","68,7%","1451,5","369,8","25,5%",GOP,"19970,2","14057,3","5912,9","42,1%","13341,9","6628,3","49,7%"
37,"45,0%","33,1%",,"11,9 pts","37,9%",,"7,1 pts",GOP %,"44,7%","38,3%",,"6,4 pts","41,4%",,"3,3 pts"
38,"313,8","42,8","271,0",,"83,2","230,6","277,0%",Net Profit,"313,8","692,4","(378,6)","(54,7%)","83,2",,-
39,"7,8%","1,3%",,"6,4 pts","2,2%",,"5,6 pts",% of Revenue,"0,7%","1,9%",,"(1,2 pts)","0,3%",,"0,4 pts"
40,"17,2%","4,0%",,"13,3 pts","5,7%",,"11,5 pts",% of GOP,"1,6%","4,9%",,"(3,4 pts)","0,6%",,"0,9 pts"